### PR TITLE
Sort deltas by name within groups

### PR DESCRIPTION
**Pull request by elemoine**
This PR suggests sorting deltas by name within (version, type) groups.

Currently the order of deltas within a (version, type) group depends on the order of the list returned by `listdir`. And that order is system-dependent.

So this PR changes the sort key to use (version, type, name) rather than (version, type), making sure that deltas are sorted by their names within (version, type) groups.

I am happy to add tests for this, but I don't know how to run the tests a this point. See https://github.com/opengisch/pum/issues/21.

### CODE REVIEW

**Comment by marioba** [comment]
@elemoine good idea.
Let me know when you're ok with the tests.

**Comment by elemoine** [comment]
Thank you. I'll write tests later today.

**Comment by elemoine** [comment]
I added tests. The `test_upgrader_run` test fails without my change to the sort key, and it passes with my change. I also added a number of minor fixes. For example, some files were not closed.

**Comment by marioba** [comment]
Great, thanks.

**Comment by marioba** [comment]
Released into version 0.5.10

**Pull request merged**
